name: boojoo
description: A Flutter application for self development.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rounded_loading_button: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^3.0.3
  persian_datepicker: any
  jalali_calendar: ^1.0.4
  curved_navigation_bar: ^0.3.3
  ff_navigation_bar: any
  flutter_local_notifications: any
  sqflite: ^2.0.0+3
  path_provider: any
  intl:
  persian_datetime_picker: 2.1.1
  numberpicker: ^2.1.1
  shared_preferences: any
  flutter_circular_chart: any
  font_awesome_flutter: any
  flutter_rating_bar: any
  flutter_statusbarcolor: any
  path: ^1.8.0
  toggle_switch: ^0.1.9
  after_layout: ^1.1.0
  flutter_onboard: any
  animated_text_kit: ^4.2.1

  auto_direction: ^0.0.5
  video_player: ^2.1.1
  fl_chart: ^0.36.1
  pie_chart: ^5.0.0

  http: ^0.12.0+2
  ant_icons: any
  icon_picker: ^2.0.0
  multi_select_flutter: ^4.0.0

  connectivity: ^3.0.6
  another_flushbar: ^1.10.22
  charts_flutter: ^0.10.0
  image_picker: ^0.6.7+22
  random_color: ^1.0.5

<<<<<<< HEAD
  flutter_speed_dial: any

=======
>>>>>>> 9fdef8eedc2657b35673a5668abd7e9ece27cfae
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: calibri
      fonts:
        - asset: assets/fonts/calibrib.ttf
          weight: 600
        - asset: assets/fonts/calibril.ttf
          weight: 400
  assets:
    - assets/img/mars.png
    - assets/img/neptune.png
    - assets/img/moon.png
    - assets/img/earth.png
    - assets/img/mercury.png
    - assets/img/day.png
    - assets/img/end.png
    - assets/img/start.png
    - assets/img/like.png
    - assets/img/num.png
    - assets
#   fonts:
#     - family: calibri
#       fonts:
#         - asset: assets/fonts/calibrb.ttf
##         - asset: fonts/calibrii.ttf
##         - asset: fonts/calibril.ttf
##         - asset: fonts/calibrili.ttf
##         - asset: fonts/calibriz.ttf






